### ISSUE TITLE
Please expose 'disableExecuteApiEndpoint' in the aws-apigateway:RestAPI provider

### ISSUE THREAD

**Issue by jamest-pin** [pulumi/pulumi-aws-apigateway#117]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I need to access this property https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/restapi/#disableexecuteapiendpoint_yaml

It would suck to have to build out my whole setup using the manual provider, that is working so nicely with the Crosswalk provider, just to use this one property. 😃 

In fact, I wish there could be a way to access any input property of the underlying resource dynamically. For example something like this maybe

```yaml
resources:
  ##
  # Payments
  # A REST API to route requests to the payments Lambda functions
  api_payments:
    type: aws-apigateway:RestAPI
    options:
      version: 2.0.1
    properties:
      stageName: ${pulumi.stack}
      routes:
        ##
        # Lambda targets
        ##
        - eventHandler: ${lambda_test_cde} #${lambda_payment_auth_callback}
          method: GET
          path: api/auth/callback
       indexIntoAPI: # modify the underlying api resource directly
         description: "Rest API Description"
         disableExecuteApiEndpoint: true
```
Alternatively, give a way to take the object in yaml, that updates the object after creation.
Something like this maybe:
```yaml
resources:
  # https://www.pulumi.com/registry/packages/aws-apigateway/api-docs/restapi/
  api_payments:
    [...]

  # https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/restapi/
  api_payments_modification:
    type: aws:apigateway:RestApi
    uses: ${api_payments.api}
    properties:
      description: "My RestAPI description"
      disableExecuteApiEndpoint: true
```

Thanks in advance
