### ISSUE TITLE
Add extra headers in default integration response in route created via localpath

### ISSUE THREAD

**Issue by raymzag** [pulumi/pulumi-aws-apigateway#165]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We have this current setup to host frontend app from S3 via API Gateway. This default routes also gets created with default integration response. 

We would like to add extra headers in the response headers such as `X-Content-Type-Options: nosniff`

```yml
  api_app:
    type: aws-apigateway:RestAPI
    properties:
      routes:
        - localPath: ${confFrontendCompiledFilesPath}
          method: GET
          path: /
```

![Image](https://github.com/user-attachments/assets/3580c3be-3f3a-4468-b3c4-0be5e0796faa)
